apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "trivy-scanner.example.com"
webhooks:
- name: "trivy-scanner.example.com"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    url: https://my_hostname:443/validate
    caBundle: "LStLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURjakNDQWxxZ0F3SUJBZ0lVUTZPVmRCdWxablVCZzZubkZ1U1o1VTJGcjFvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1FqRUxNQWtHQTFVRUJoTUNXRmd4RlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRQpDZ3dUUkdWbVlYVnNkQ0JEYjIxd1lXNTVJRXgwWkRBZUZ3MHlNakExTWpVeE1ERTJNakZhRncwek1qQTFNakl4Ck1ERTJNakZhTURReE1qQXdCZ05WQkFNTUtXdDJiUzB3TkMxbmRXVnpkREkzTG1oMk1pNXNZV0l1Wlc1bkxtSnYKY3k1eVpXUm9ZWFF1WTI5dE1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBemRsZQo5Q2xNa1d3d0JhY3diMUFJTmZZTlZkN1pUV1M3d2pidi9XRUpMazUzSCtPK1lkUStyV25YTW1Tb0w3QklRQlovCkJ2aUJHRzJzMFdpa05ld3hrdFRveTRXVTVLY2RjZnZFc3ZFRFFEREM4czJieEJ5UTNnOEpUZlcwdy9GS1luYUgKOGowSHpJOTFNRTRSYk9jai9WNWxwbms2SjR1M3JUQ0ROVjNZVmplQTJBVnNJMW96S2p6RzZFL2dxSnlEemJRNAp5VDJ0OStLeGZ1QXNsSmdORVdiUkxYTDUyQVpySWp4RGNUN2FpcDBySlN4dmdpRGV5eHVCc1ovS0ZYU0VkN0k1CkJnek1LSjc3M1RSdWowc0FBTXdKR2dwY3RkNDdiVDBVQnVFS3JjekpCNENkME9tWSs3THdjN001ZHc0NTlxaGEKTzVnaE14NytybTU3VzFlYmZRSURBUUFCbzI0d2JEQTBCZ05WSFJFRUxUQXJnaWxyZG0wdE1EUXRaM1ZsYzNReQpOeTVvZGpJdWJHRmlMbVZ1Wnk1aWIzTXVjbVZrYUdGMExtTnZiVEEwQmdOVkhSRUVMVEFyZ2lscmRtMHRNRFF0ClozVmxjM1F5Tnk1b2RqSXViR0ZpTG1WdVp5NWliM011Y21Wa2FHRjBMbU52YlRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUF0WVFFMlIxeW5JZzdsYkRvemFoR1I3cUx2SXYyUUpyTHRNYUtNaldNeFZKWC9GUldjb3h1U1g0VApKbkJHd0prYzdZWjZpdTU1TWJYa0gzbkhSZGJ1THhqcUpIbEhXdFBEYXJvaGNGSDVpNlRySUw2cVhaenBRRllTCmMvbkNvMjFpV3FBSkZWVHNRZmtaQzVpbWxQdGM1VHVqN1kzbFBCR1c1M1JUbkF6elQ3Skdla1NUQXh6MG1hUTgKQVJvQkFZV2o0ZlZVRlA5aFEyZ2Z1aW9ONy9xYVE5WjQrZGt1clZpYyswcUFFZkxMUnFjYXZpMFJ1UzNjRWMvTQphYzZaaVZScHpVcmJXVGI2aE92bWNWUk4yVTVGdFlFdTJzQUc5TG1qZUxRcDU0VDkwdnN6c3NhVzNFcWRjSWxnCnhrM2NVZU03ejRwUC9KZkVJMVZuSkhiaVk2d3RwZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  timeoutSeconds: 5
